apiVersion: v1 
kind: Pod 
metadata: 
    name: dind 
spec: 
    containers: 
      - name: docker-cmds 
        image: docker:1.12.6 
        command: ['tail', '-f', '/dev/null'] 
        resources: 
            requests: 
                cpu: 10m 
                memory: 256Mi 
        env: 
          - name: DOCKER_HOST 
            value: tcp://localhost:2375 
      - name: dind-daemon 
        image: docker:1.12.6-dind 
        resources: 
            requests: 
                cpu: 20m 
                memory: 512Mi 
        securityContext: 
            privileged: true 
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker 
          - mountPath: /.kube/config
            name: kube-config
          - mountPath: /working-dir
            name: working-dir
    volumes: 
      - name: docker-graph-storage 
        emptyDir: {}
      - name: kube-config
        hostPath:
            path: $HOME/.kube/config
      - name: working-dir
        hostPath:
            path: $PWD
